### ISSUE TITLE
Remove quotes from model links

### ISSUE THREAD

**Issue by Clashsoft** [fujaba/fulibWorkflows#5]
The Model docs provide this example:

```yaml
- data: Room r1
  topic: math
  credits: 17
  neighbors: "[r2, r5]"
  neighbors.back: "[neighbors]"
```

The " " are kinda bothersome. Yaml already supports lists with [ ].

In addition I'd like to use brackets in my string literals:

```yaml
- data: Room r1
  topic: math
  credits: 17
  description: "[TODO] Write this"
```

But the object diagram looks like this 😢 

<img width="267" alt="Screenshot 2022-02-28 at 15 07 04" src="https://user-images.githubusercontent.com/4145923/155996807-c3a16d0b-63cf-450e-b3dc-1d415a199baa.png">
